export const ISLOADING = 'ISLOADING';
export const LOADING = 'ISLOADING';
export const FETCHING_POST = 'FETCHING_USERS';
export const FETCHING_ERROR = 'FETCHING_ERROR';
export const FETCHING_USER_DETAIL = 'FETCHING_USER_DETAIL';
